### ISSUE TITLE
Question: Is this exactly version available in pip (pypi) somewhere?

### ISSUE THREAD

**Issue by thiagoghisi** [dw/python-geoip#1]
Hey @dw,

Is this exactly version of python-geoip available in pip (pypi) somewhere? I found it really useful, but I just don't want to copy it directly to my project.

Thanks!

**Comment by dw** [comment]
Hi there,

Yes, it's available under the (rather regrettable) name https://pypi.python.org/pypi/Pure-Python-GeoIP-Library/0.1

**Comment by thiagoghisi** [comment]
Thanks for pointing that out @dw.

But, it looks like, as Google Code has been shutdown the download_url is broken.

See:

https://pypi.python.org/pypi/Pure-Python-GeoIP-Library/json

Also, if possible, can you republish that as a tarball inside pypi? 
I'm sure you know that, but here is a good example: https://pypi.python.org/pypi/requests/json

Thanks!

**Comment by thiagoghisi** [comment]
Hi @dw,

http://python-geoip.googlecode.com/hg/pygeoip.py is now returning a 404 and not allowing people to just install Pure-Python-GeoIP-Library using a simple: 

`pip install Pure-Python-GeoIP-Library`

Do you need any help making that available on pip/pypi? I would be more than happy to do that if you make me temporarily a maintainer. My username on pypi is thiagoghisi.

Thanks a lot!

**Comment by dw** [comment]
Sorry about the wait! Should be all fixed up now. Sadly I registered this package on PyPI before it became so commonplace to use it with pip, so the package name kinda sucks, but we're stuck with it. :) Please reopen if you have any further issues

**Comment by thiagoghisi** [comment]
No problem at all.

Awesome! Thanks a lot!
